export const GET_CONTACTS = "GET_CONTACTS";
export const TOGGLE_ADD_CONTACTS_FORM = "TOGGLE_ADD_CONTACTS_FORM";
export const ADD_CONTACT = "ADD_CONTACT";
export const TOGGLE_MAILING_LIST_FORM = "TOGGLE_MAILING_LIST_FORM";
export const CREATE_MAILING_LIST = "CREATE_MAILING_LIST";