export const GET_CONTACTS = "GET_CONTACTS";
export const TOGGLE_ADD_CONTACTS_FORM = "TOGGLE_ADD_CONTACTS_FORM";
export const ADD_CONTACT = "ADD_CONTACT";
export const TOGGLE_MAILING_LIST_FORM = "TOGGLE_MAILING_LIST_FORM";
export const CREATE_MAILING_LIST = "CREATE_MAILING_LIST";
export const CLOSE_RESPONSE_MESSAGE = "CLOSE_RESPONSE_MESSAGE";
export const TOGGLE_EDIT_CONTACTS_FORM = "TOGGLE_EDIT_CONTACTS_FORM";
export const EDIT_CONTACT = "EDIT_CONTACT";
